services:
  db:
    image: postgres:16
    container_name: leetgame_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: leetgame
      POSTGRES_USER: leetgame_user
      POSTGRES_PASSWORD: leetgame_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: