# Generated by Django 6.0.3 on 2026-03-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_leveltestcase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['chapter_order', 'order']},
        ),
        migrations.RemoveField(
            model_name='level',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='level',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='level',
            name='chapter',
            field=models.CharField(default='Chapter 1', max_length=100),
        ),
        migrations.AddField(
            model_name='level',
            name='chapter_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='level',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='level',
            name='node_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('boss', 'Boss')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='level',
            name='function_name',
            field=models.CharField(max_length=100),
        ),
    ]
