# Generated by Django 6.0.3 on 2026-03-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0003_alter_level_options_remove_level_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
