from django.core.management.base import BaseCommand
from levels.models import Level, LevelTestCase


def test(input_data, expected_output, order, is_hidden=False):
    return {
        "input_data": input_data,
        "expected_output": expected_output,
        "is_hidden": is_hidden,
        "order": order,
    }


LEVELS_DATA = [
    # ===========================
    # Chapter 1 — Arrays
    # ===========================
    {
        "title": "Two Sum",
        "slug": "two-sum",
        "description": "Return the indices of the two numbers whose sum equals target.",
        "difficulty": "easy",
        "order": 1,
        "chapter": "Arrays",
        "chapter_order": 1,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def two_sum(self, nums, target):\n        pass\n",
        "function_name": "two_sum",
        "is_active": True,
        "tests": [
            test([[2, 7, 11, 15], 9], [0, 1], 1),
            test([[3, 2, 4], 6], [1, 2], 2),
            test([[3, 3], 6], [0, 1], 3, is_hidden=True),
        ],
    },
    {
        "title": "Contains Duplicate",
        "slug": "contains-duplicate",
        "description": "Return true if any value appears more than once in the array.",
        "difficulty": "easy",
        "order": 2,
        "chapter": "Arrays",
        "chapter_order": 1,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def contains_duplicate(self, nums):\n        pass\n",
        "function_name": "contains_duplicate",
        "is_active": True,
        "tests": [
            test([[1, 2, 3, 1]], True, 1),
            test([[1, 2, 3, 4]], False, 2),
            test([[]], False, 3, is_hidden=True),
        ],
    },
    {
        "title": "Maximum Subarray",
        "slug": "maximum-subarray",
        "description": "Return the largest sum of any contiguous subarray.",
        "difficulty": "easy",
        "order": 3,
        "chapter": "Arrays",
        "chapter_order": 1,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def max_sub_array(self, nums):\n        pass\n",
        "function_name": "max_sub_array",
        "is_active": True,
        "tests": [
            test([[-2, 1, -3, 4, -1, 2, 1, -5, 4]], 6, 1),
            test([[1]], 1, 2),
            test([[-1, -2, -3, -4]], -1, 3, is_hidden=True),
        ],
    },
    {
        "title": "Product of Array Except Self",
        "slug": "product-of-array-except-self",
        "description": "Return an array where each element is the product of all other elements.",
        "difficulty": "medium",
        "order": 4,
        "chapter": "Arrays",
        "chapter_order": 1,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def product_except_self(self, nums):\n        pass\n",
        "function_name": "product_except_self",
        "is_active": True,
        "tests": [
            test([[1, 2, 3, 4]], [24, 12, 8, 6], 1),
            test([[-1, 1, 0, -3, 3]], [0, 0, 9, 0, 0], 2),
            test([[0, 0]], [0, 0], 3, is_hidden=True),
        ],
    },
    {
        "title": "Best Time to Buy and Sell Stock",
        "slug": "best-time-to-buy-and-sell-stock",
        "description": "Return the maximum profit from a single buy and a single sell.",
        "difficulty": "easy",
        "order": 5,
        "chapter": "Arrays",
        "chapter_order": 1,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def max_profit(self, prices):\n        pass\n",
        "function_name": "max_profit",
        "is_active": True,
        "tests": [
            test([[7, 1, 5, 3, 6, 4]], 5, 1),
            test([[7, 6, 4, 3, 1]], 0, 2),
            test([[2, 1, 2, 1, 0, 1, 2]], 2, 3, is_hidden=True),
        ],
    },
    {
        "title": "Find Pivot Index",
        "slug": "find-pivot-index",
        "description": "Return the index where the sum on the left equals the sum on the right.",
        "difficulty": "easy",
        "order": 6,
        "chapter": "Arrays",
        "chapter_order": 1,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def pivot_index(self, nums):\n        pass\n",
        "function_name": "pivot_index",
        "is_active": True,
        "tests": [
            test([[1, 7, 3, 6, 5, 6]], 3, 1),
            test([[1, 2, 3]], -1, 2),
            test([[-1, -1, -1, 0, 1, 1]], 0, 3, is_hidden=True),
        ],
    },
    {
        "title": "Majority Element",
        "slug": "majority-element",
        "description": "Return the element that appears more than n // 2 times.",
        "difficulty": "easy",
        "order": 7,
        "chapter": "Arrays",
        "chapter_order": 1,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def majority_element(self, nums):\n        pass\n",
        "function_name": "majority_element",
        "is_active": True,
        "tests": [
            test([[3, 2, 3]], 3, 1),
            test([[2, 2, 1, 1, 1, 2, 2]], 2, 2),
            test([[1]], 1, 3, is_hidden=True),
        ],
    },
    {
        "title": "Missing Number",
        "slug": "missing-number",
        "description": "Return the missing number from the range [0, n].",
        "difficulty": "easy",
        "order": 8,
        "chapter": "Arrays",
        "chapter_order": 1,
        "node_type": "boss",
        "starter_code_python": "class Solution:\n    def missing_number(self, nums):\n        pass\n",
        "function_name": "missing_number",
        "is_active": True,
        "tests": [
            test([[3, 0, 1]], 2, 1),
            test([[0, 1]], 2, 2),
            test([[9, 6, 4, 2, 3, 5, 7, 0, 1]], 8, 3, is_hidden=True),
        ],
    },

    # ===========================
    # Chapter 2 — Hashing
    # ===========================
    {
        "title": "Valid Anagram",
        "slug": "valid-anagram",
        "description": "Return true if t is an anagram of s.",
        "difficulty": "easy",
        "order": 9,
        "chapter": "Hashing",
        "chapter_order": 2,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def is_anagram(self, s, t):\n        pass\n",
        "function_name": "is_anagram",
        "is_active": True,
        "tests": [
            test(["anagram", "nagaram"], True, 1),
            test(["rat", "car"], False, 2),
            test(["", ""], True, 3, is_hidden=True),
        ],
    },
    {
        "title": "Ransom Note",
        "slug": "ransom-note",
        "description": "Return true if ransom_note can be constructed using the letters in magazine.",
        "difficulty": "easy",
        "order": 10,
        "chapter": "Hashing",
        "chapter_order": 2,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def can_construct(self, ransom_note, magazine):\n        pass\n",
        "function_name": "can_construct",
        "is_active": True,
        "tests": [
            test(["a", "b"], False, 1),
            test(["aa", "aab"], True, 2),
            test(["hello", "helo"], False, 3, is_hidden=True),
        ],
    },
    {
        "title": "Isomorphic Strings",
        "slug": "isomorphic-strings",
        "description": "Return true if there is a one-to-one mapping between the characters of s and t.",
        "difficulty": "easy",
        "order": 11,
        "chapter": "Hashing",
        "chapter_order": 2,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def is_isomorphic(self, s, t):\n        pass\n",
        "function_name": "is_isomorphic",
        "is_active": True,
        "tests": [
            test(["egg", "add"], True, 1),
            test(["foo", "bar"], False, 2),
            test(["paper", "title"], True, 3, is_hidden=True),
        ],
    },
    {
        "title": "Word Pattern",
        "slug": "word-pattern",
        "description": "Return true if the words in s follow the same pattern.",
        "difficulty": "easy",
        "order": 12,
        "chapter": "Hashing",
        "chapter_order": 2,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def word_pattern(self, pattern, s):\n        pass\n",
        "function_name": "word_pattern",
        "is_active": True,
        "tests": [
            test(["abba", "dog cat cat dog"], True, 1),
            test(["abba", "dog cat cat fish"], False, 2),
            test(["abba", "dog dog dog dog"], False, 3, is_hidden=True),
        ],
    },
    {
        "title": "Happy Number",
        "slug": "happy-number",
        "description": "Return true if n is a happy number.",
        "difficulty": "easy",
        "order": 13,
        "chapter": "Hashing",
        "chapter_order": 2,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def is_happy(self, n):\n        pass\n",
        "function_name": "is_happy",
        "is_active": True,
        "tests": [
            test([19], True, 1),
            test([2], False, 2),
            test([1], True, 3, is_hidden=True),
        ],
    },
    {
        "title": "Longest Consecutive Sequence",
        "slug": "longest-consecutive-sequence",
        "description": "Return the length of the longest consecutive sequence.",
        "difficulty": "medium",
        "order": 14,
        "chapter": "Hashing",
        "chapter_order": 2,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def longest_consecutive(self, nums):\n        pass\n",
        "function_name": "longest_consecutive",
        "is_active": True,
        "tests": [
            test([[100, 4, 200, 1, 3, 2]], 4, 1),
            test([[0, 3, 7, 2, 5, 8, 4, 6, 0, 1]], 9, 2),
            test([[]], 0, 3, is_hidden=True),
        ],
    },
    {
        "title": "Find the Difference",
        "slug": "find-the-difference",
        "description": "Return the extra letter in t.",
        "difficulty": "easy",
        "order": 15,
        "chapter": "Hashing",
        "chapter_order": 2,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def find_the_difference(self, s, t):\n        pass\n",
        "function_name": "find_the_difference",
        "is_active": True,
        "tests": [
            test(["abcd", "abcde"], "e", 1),
            test(["", "y"], "y", 2),
            test(["xyz", "xyzz"], "z", 3, is_hidden=True),
        ],
    },
    {
        "title": "First Unique Character in a String",
        "slug": "first-unique-character-in-a-string",
        "description": "Return the index of the first non-repeating character, or -1 if none exists.",
        "difficulty": "easy",
        "order": 16,
        "chapter": "Hashing",
        "chapter_order": 2,
        "node_type": "boss",
        "starter_code_python": "class Solution:\n    def first_uniq_char(self, s):\n        pass\n",
        "function_name": "first_uniq_char",
        "is_active": True,
        "tests": [
            test(["leetcode"], 0, 1),
            test(["loveleetcode"], 2, 2),
            test(["aabb"], -1, 3, is_hidden=True),
        ],
    },

    # ===========================
    # Chapter 3 — Strings
    # ===========================
    {
        "title": "Valid Palindrome",
        "slug": "valid-palindrome",
        "description": "Return true if s is a palindrome after ignoring non-alphanumeric characters and letter case.",
        "difficulty": "easy",
        "order": 17,
        "chapter": "Strings",
        "chapter_order": 3,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def is_palindrome(self, s):\n        pass\n",
        "function_name": "is_palindrome",
        "is_active": True,
        "tests": [
            test(["A man, a plan, a canal: Panama"], True, 1),
            test(["race a car"], False, 2),
            test(["0P"], False, 3, is_hidden=True),
        ],
    },
    {
        "title": "Longest Common Prefix",
        "slug": "longest-common-prefix",
        "description": "Return the longest common prefix among all strings in the array.",
        "difficulty": "easy",
        "order": 18,
        "chapter": "Strings",
        "chapter_order": 3,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def longest_common_prefix(self, strs):\n        pass\n",
        "function_name": "longest_common_prefix",
        "is_active": True,
        "tests": [
            test([["flower", "flow", "flight"]], "fl", 1),
            test([["dog", "racecar", "car"]], "", 2),
            test([["ab", "a"]], "a", 3, is_hidden=True),
        ],
    },
    {
        "title": "Merge Strings Alternately",
        "slug": "merge-strings-alternately",
        "description": "Merge two strings by alternating their characters.",
        "difficulty": "easy",
        "order": 19,
        "chapter": "Strings",
        "chapter_order": 3,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def merge_alternately(self, word1, word2):\n        pass\n",
        "function_name": "merge_alternately",
        "is_active": True,
        "tests": [
            test(["abc", "pqr"], "apbqcr", 1),
            test(["ab", "pqrs"], "apbqrs", 2),
            test(["", "xyz"], "xyz", 3, is_hidden=True),
        ],
    },
    {
        "title": "Reverse Words in a String III",
        "slug": "reverse-words-in-a-string-iii",
        "description": "Reverse the characters of each word in the sentence.",
        "difficulty": "easy",
        "order": 20,
        "chapter": "Strings",
        "chapter_order": 3,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def reverse_words(self, s):\n        pass\n",
        "function_name": "reverse_words",
        "is_active": True,
        "tests": [
            test(["Let's take LeetCode contest"], "s'teL ekat edoCteeL tsetnoc", 1),
            test(["God Ding"], "doG gniD", 2),
            test(["hello"], "olleh", 3, is_hidden=True),
        ],
    },
    {
        "title": "Length of Last Word",
        "slug": "length-of-last-word",
        "description": "Return the length of the last word in the string.",
        "difficulty": "easy",
        "order": 21,
        "chapter": "Strings",
        "chapter_order": 3,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def length_of_last_word(self, s):\n        pass\n",
        "function_name": "length_of_last_word",
        "is_active": True,
        "tests": [
            test(["Hello World"], 5, 1),
            test(["   fly me   to   the moon  "], 4, 2),
            test(["a"], 1, 3, is_hidden=True),
        ],
    },
    {
        "title": "Roman to Integer",
        "slug": "roman-to-integer",
        "description": "Convert a Roman numeral to an integer.",
        "difficulty": "easy",
        "order": 22,
        "chapter": "Strings",
        "chapter_order": 3,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def roman_to_int(self, s):\n        pass\n",
        "function_name": "roman_to_int",
        "is_active": True,
        "tests": [
            test(["III"], 3, 1),
            test(["LVIII"], 58, 2),
            test(["MCMXCIV"], 1994, 3, is_hidden=True),
        ],
    },
    {
        "title": "Valid Palindrome II",
        "slug": "valid-palindrome-ii",
        "description": "Return true if the string can become a palindrome after deleting at most one character.",
        "difficulty": "easy",
        "order": 23,
        "chapter": "Strings",
        "chapter_order": 3,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def valid_palindrome(self, s):\n        pass\n",
        "function_name": "valid_palindrome",
        "is_active": True,
        "tests": [
            test(["aba"], True, 1),
            test(["abca"], True, 2),
            test(["abc"], False, 3, is_hidden=True),
        ],
    },
    {
        "title": "Zigzag Conversion",
        "slug": "zigzag-conversion",
        "description": "Write the string in a zigzag pattern and return it row by row.",
        "difficulty": "medium",
        "order": 24,
        "chapter": "Strings",
        "chapter_order": 3,
        "node_type": "boss",
        "starter_code_python": "class Solution:\n    def convert(self, s, num_rows):\n        pass\n",
        "function_name": "convert",
        "is_active": True,
        "tests": [
            test(["PAYPALISHIRING", 3], "PAHNAPLSIIGYIR", 1),
            test(["PAYPALISHIRING", 4], "PINALSIGYAHRPI", 2),
            test(["ABCDE", 2], "ACEBD", 3, is_hidden=True),
        ],
    },

    # ===========================
    # Chapter 4 — Stacks
    # ===========================
    {
        "title": "Valid Parentheses",
        "slug": "valid-parentheses",
        "description": "Return true if the brackets are balanced and properly nested.",
        "difficulty": "easy",
        "order": 25,
        "chapter": "Stacks",
        "chapter_order": 4,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def is_valid(self, s):\n        pass\n",
        "function_name": "is_valid",
        "is_active": True,
        "tests": [
            test(["()"], True, 1),
            test(["()[]{}"], True, 2),
            test(["([)]"], False, 3, is_hidden=True),
        ],
    },
    {
        "title": "Baseball Game",
        "slug": "baseball-game",
        "description": "Return the total score after processing the operations.",
        "difficulty": "easy",
        "order": 26,
        "chapter": "Stacks",
        "chapter_order": 4,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def cal_points(self, operations):\n        pass\n",
        "function_name": "cal_points",
        "is_active": True,
        "tests": [
            test([["5", "2", "C", "D", "+"]], 30, 1),
            test([["5", "-2", "4", "C", "D", "9", "+", "+"]], 27, 2),
            test([["1", "C"]], 0, 3, is_hidden=True),
        ],
    },
    {
        "title": "Remove All Adjacent Duplicates in String",
        "slug": "remove-all-adjacent-duplicates-in-string",
        "description": "Repeatedly remove adjacent duplicate characters until none remain.",
        "difficulty": "easy",
        "order": 27,
        "chapter": "Stacks",
        "chapter_order": 4,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def remove_duplicates(self, s):\n        pass\n",
        "function_name": "remove_duplicates",
        "is_active": True,
        "tests": [
            test(["abbaca"], "ca", 1),
            test(["azxxzy"], "ay", 2),
            test(["abba"], "", 3, is_hidden=True),
        ],
    },
    {
        "title": "Make the String Great",
        "slug": "make-the-string-great",
        "description": "Remove adjacent letters that are the same character with opposite case until the string is good.",
        "difficulty": "easy",
        "order": 28,
        "chapter": "Stacks",
        "chapter_order": 4,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def make_good(self, s):\n        pass\n",
        "function_name": "make_good",
        "is_active": True,
        "tests": [
            test(["leEeetcode"], "leetcode", 1),
            test(["abBAcC"], "", 2),
            test(["Pp"], "", 3, is_hidden=True),
        ],
    },
    {
        "title": "Backspace String Compare",
        "slug": "backspace-string-compare",
        "description": "Return true if the two strings are equal after processing backspaces.",
        "difficulty": "easy",
        "order": 29,
        "chapter": "Stacks",
        "chapter_order": 4,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def backspace_compare(self, s, t):\n        pass\n",
        "function_name": "backspace_compare",
        "is_active": True,
        "tests": [
            test(["ab#c", "ad#c"], True, 1),
            test(["ab##", "c#d#"], True, 2),
            test(["a#c", "b"], False, 3, is_hidden=True),
        ],
    },
    {
        "title": "Min Add to Make Parentheses Valid",
        "slug": "min-add-to-make-parentheses-valid",
        "description": "Return the minimum number of parentheses needed to make the string valid.",
        "difficulty": "medium",
        "order": 30,
        "chapter": "Stacks",
        "chapter_order": 4,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def min_add_to_make_valid(self, s):\n        pass\n",
        "function_name": "min_add_to_make_valid",
        "is_active": True,
        "tests": [
            test(["())"], 1, 1),
            test(["((("], 3, 2),
            test(["()))(("], 4, 3, is_hidden=True),
        ],
    },
    {
        "title": "Evaluate Reverse Polish Notation",
        "slug": "evaluate-reverse-polish-notation",
        "description": "Evaluate an arithmetic expression written in Reverse Polish Notation.",
        "difficulty": "medium",
        "order": 31,
        "chapter": "Stacks",
        "chapter_order": 4,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def eval_rpn(self, tokens):\n        pass\n",
        "function_name": "eval_rpn",
        "is_active": True,
        "tests": [
            test([["2", "1", "+", "3", "*"]], 9, 1),
            test([["4", "13", "5", "/", "+"]], 6, 2),
            test([["5"]], 5, 3, is_hidden=True),
        ],
    },
    {
        "title": "Decode String",
        "slug": "decode-string",
        "description": "Decode an encoded string such as 3[a2[c]].",
        "difficulty": "medium",
        "order": 32,
        "chapter": "Stacks",
        "chapter_order": 4,
        "node_type": "boss",
        "starter_code_python": "class Solution:\n    def decode_string(self, s):\n        pass\n",
        "function_name": "decode_string",
        "is_active": True,
        "tests": [
            test(["3[a]2[bc]"], "aaabcbc", 1),
            test(["3[a2[c]]"], "accaccacc", 2),
            test(["10[a]"], "aaaaaaaaaa", 3, is_hidden=True),
        ],
    },

    # ===========================
    # Chapter 5 — Binary Search
    # ===========================
    {
        "title": "Binary Search",
        "slug": "binary-search",
        "description": "Return the index of target in a sorted array, or -1 if it is not present.",
        "difficulty": "easy",
        "order": 33,
        "chapter": "Binary Search",
        "chapter_order": 5,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def search(self, nums, target):\n        pass\n",
        "function_name": "search",
        "is_active": True,
        "tests": [
            test([[-1, 0, 3, 5, 9, 12], 9], 4, 1),
            test([[-1, 0, 3, 5, 9, 12], 2], -1, 2),
            test([[5], 5], 0, 3, is_hidden=True),
        ],
    },
    {
        "title": "Search Insert Position",
        "slug": "search-insert-position",
        "description": "Return the index of target, or the position where it should be inserted.",
        "difficulty": "easy",
        "order": 34,
        "chapter": "Binary Search",
        "chapter_order": 5,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def search_insert(self, nums, target):\n        pass\n",
        "function_name": "search_insert",
        "is_active": True,
        "tests": [
            test([[1, 3, 5, 6], 5], 2, 1),
            test([[1, 3, 5, 6], 2], 1, 2),
            test([[1], 0], 0, 3, is_hidden=True),
        ],
    },
    {
        "title": "Sqrt(x)",
        "slug": "sqrtx",
        "description": "Return the integer square root of x.",
        "difficulty": "easy",
        "order": 35,
        "chapter": "Binary Search",
        "chapter_order": 5,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def my_sqrt(self, x):\n        pass\n",
        "function_name": "my_sqrt",
        "is_active": True,
        "tests": [
            test([4], 2, 1),
            test([8], 2, 2),
            test([15], 3, 3, is_hidden=True),
        ],
    },
    {
        "title": "Arrange Coins",
        "slug": "arrange-coins",
        "description": "Return the number of complete staircase rows that can be formed.",
        "difficulty": "easy",
        "order": 36,
        "chapter": "Binary Search",
        "chapter_order": 5,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def arrange_coins(self, n):\n        pass\n",
        "function_name": "arrange_coins",
        "is_active": True,
        "tests": [
            test([5], 2, 1),
            test([8], 3, 2),
            test([10], 4, 3, is_hidden=True),
        ],
    },
    {
        "title": "Find Smallest Letter Greater Than Target",
        "slug": "find-smallest-letter-greater-than-target",
        "description": "Return the smallest character that is lexicographically greater than target.",
        "difficulty": "easy",
        "order": 37,
        "chapter": "Binary Search",
        "chapter_order": 5,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def next_greatest_letter(self, letters, target):\n        pass\n",
        "function_name": "next_greatest_letter",
        "is_active": True,
        "tests": [
            test([["c", "f", "j"], "a"], "c", 1),
            test([["c", "f", "j"], "c"], "f", 2),
            test([["c", "f", "j"], "j"], "c", 3, is_hidden=True),
        ],
    },
    {
        "title": "Peak Index in Mountain Array",
        "slug": "peak-index-in-mountain-array",
        "description": "Return the index of the peak in a mountain array.",
        "difficulty": "easy",
        "order": 38,
        "chapter": "Binary Search",
        "chapter_order": 5,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def peak_index_in_mountain_array(self, arr):\n        pass\n",
        "function_name": "peak_index_in_mountain_array",
        "is_active": True,
        "tests": [
            test([[0, 1, 0]], 1, 1),
            test([[0, 2, 1, 0]], 1, 2),
            test([[3, 4, 5, 1]], 2, 3, is_hidden=True),
        ],
    },
    {
        "title": "Search in Rotated Sorted Array",
        "slug": "search-in-rotated-sorted-array",
        "description": "Return the index of target in a rotated sorted array, or -1 if it is not present.",
        "difficulty": "medium",
        "order": 39,
        "chapter": "Binary Search",
        "chapter_order": 5,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def search(self, nums, target):\n        pass\n",
        "function_name": "search",
        "is_active": True,
        "tests": [
            test([[4, 5, 6, 7, 0, 1, 2], 0], 4, 1),
            test([[4, 5, 6, 7, 0, 1, 2], 3], -1, 2),
            test([[5, 1, 3], 5], 0, 3, is_hidden=True),
        ],
    },
    {
        "title": "Koko Eating Bananas",
        "slug": "koko-eating-bananas",
        "description": "Return the minimum eating speed needed to finish all bananas within h hours.",
        "difficulty": "medium",
        "order": 40,
        "chapter": "Binary Search",
        "chapter_order": 5,
        "node_type": "boss",
        "starter_code_python": "class Solution:\n    def min_eating_speed(self, piles, h):\n        pass\n",
        "function_name": "min_eating_speed",
        "is_active": True,
        "tests": [
            test([[3, 6, 7, 11], 8], 4, 1),
            test([[30, 11, 23, 4, 20], 5], 30, 2),
            test([[30, 11, 23, 4, 20], 6], 23, 3, is_hidden=True),
        ],
    },

    # ===========================
    # Chapter 6 — Sliding Window
    # ===========================
    {
        "title": "Maximum Average Subarray I",
        "slug": "maximum-average-subarray-i",
        "description": "Return the maximum average value of any contiguous subarray of length k.",
        "difficulty": "easy",
        "order": 41,
        "chapter": "Sliding Window",
        "chapter_order": 6,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def find_max_average(self, nums, k):\n        pass\n",
        "function_name": "find_max_average",
        "is_active": True,
        "tests": [
            test([[1, 12, -5, -6, 50, 3], 4], 12.75, 1),
            test([[5], 1], 5.0, 2),
            test([[-1, -12, -5, -6, -50, -3], 2], -5.5, 3, is_hidden=True),
        ],
    },
    {
        "title": "Longest Substring Without Repeating Characters",
        "slug": "longest-substring-without-repeating-characters",
        "description": "Return the length of the longest substring without repeating characters.",
        "difficulty": "medium",
        "order": 42,
        "chapter": "Sliding Window",
        "chapter_order": 6,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def length_of_longest_substring(self, s):\n        pass\n",
        "function_name": "length_of_longest_substring",
        "is_active": True,
        "tests": [
            test(["abcabcbb"], 3, 1),
            test(["bbbbb"], 1, 2),
            test([""], 0, 3, is_hidden=True),
        ],
    },
    {
        "title": "Permutation in String",
        "slug": "permutation-in-string",
        "description": "Return true if s2 contains a permutation of s1.",
        "difficulty": "medium",
        "order": 43,
        "chapter": "Sliding Window",
        "chapter_order": 6,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def check_inclusion(self, s1, s2):\n        pass\n",
        "function_name": "check_inclusion",
        "is_active": True,
        "tests": [
            test(["ab", "eidbaooo"], True, 1),
            test(["ab", "eidboaoo"], False, 2),
            test(["adc", "dcda"], True, 3, is_hidden=True),
        ],
    },
    {
        "title": "Minimum Size Subarray Sum",
        "slug": "minimum-size-subarray-sum",
        "description": "Return the minimum length of a contiguous subarray whose sum is at least target.",
        "difficulty": "medium",
        "order": 44,
        "chapter": "Sliding Window",
        "chapter_order": 6,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def min_sub_array_len(self, target, nums):\n        pass\n",
        "function_name": "min_sub_array_len",
        "is_active": True,
        "tests": [
            test([7, [2, 3, 1, 2, 4, 3]], 2, 1),
            test([4, [1, 4, 4]], 1, 2),
            test([11, [1, 1, 1, 1, 1, 1, 1, 1]], 0, 3, is_hidden=True),
        ],
    },
    {
        "title": "Longest Repeating Character Replacement",
        "slug": "longest-repeating-character-replacement",
        "description": "Return the length of the longest substring that can be made of one repeating character after at most k replacements.",
        "difficulty": "medium",
        "order": 45,
        "chapter": "Sliding Window",
        "chapter_order": 6,
        "node_type": "boss",
        "starter_code_python": "class Solution:\n    def character_replacement(self, s, k):\n        pass\n",
        "function_name": "character_replacement",
        "is_active": True,
        "tests": [
            test(["ABAB", 2], 4, 1),
            test(["AABABBA", 1], 4, 2),
            test(["ABCDE", 1], 2, 3, is_hidden=True),
        ],
    },

    # ===========================
    # Chapter 7 — Prefix Sum & Two Pointers
    # ===========================
    {
        "title": "Squares of a Sorted Array",
        "slug": "squares-of-a-sorted-array",
        "description": "Return the squares of the numbers in non-decreasing order.",
        "difficulty": "easy",
        "order": 46,
        "chapter": "Prefix Sum & Two Pointers",
        "chapter_order": 7,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def sorted_squares(self, nums):\n        pass\n",
        "function_name": "sorted_squares",
        "is_active": True,
        "tests": [
            test([[-4, -1, 0, 3, 10]], [0, 1, 9, 16, 100], 1),
            test([[-7, -3, 2, 3, 11]], [4, 9, 9, 49, 121], 2),
            test([[0]], [0], 3, is_hidden=True),
        ],
    },
    {
        "title": "Running Sum of 1D Array",
        "slug": "running-sum-of-1d-array",
        "description": "Return the running sum of the array.",
        "difficulty": "easy",
        "order": 47,
        "chapter": "Prefix Sum & Two Pointers",
        "chapter_order": 7,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def running_sum(self, nums):\n        pass\n",
        "function_name": "running_sum",
        "is_active": True,
        "tests": [
            test([[1, 2, 3, 4]], [1, 3, 6, 10], 1),
            test([[1, 1, 1, 1, 1]], [1, 2, 3, 4, 5], 2),
            test([[]], [], 3, is_hidden=True),
        ],
    },
    {
        "title": "Find Middle Index in Array",
        "slug": "find-middle-index-in-array",
        "description": "Return the leftmost index where the sum on the left equals the sum on the right.",
        "difficulty": "easy",
        "order": 48,
        "chapter": "Prefix Sum & Two Pointers",
        "chapter_order": 7,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def find_middle_index(self, nums):\n        pass\n",
        "function_name": "find_middle_index",
        "is_active": True,
        "tests": [
            test([[2, 3, -1, 8, 4]], 3, 1),
            test([[1, -1, 4]], 2, 2),
            test([[0, 0, 0]], 0, 3, is_hidden=True),
        ],
    },
    {
        "title": "Subarray Sum Equals K",
        "slug": "subarray-sum-equals-k",
        "description": "Return the number of contiguous subarrays whose sum equals k.",
        "difficulty": "medium",
        "order": 49,
        "chapter": "Prefix Sum & Two Pointers",
        "chapter_order": 7,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def subarray_sum(self, nums, k):\n        pass\n",
        "function_name": "subarray_sum",
        "is_active": True,
        "tests": [
            test([[1, 1, 1], 2], 2, 1),
            test([[1, 2, 3], 3], 2, 2),
            test([[0, 0, 0], 0], 6, 3, is_hidden=True),
        ],
    },
    {
        "title": "Maximum Count of Positive Integer and Negative Integer",
        "slug": "maximum-count-of-positive-integer-and-negative-integer",
        "description": "Return the larger of the number of positive integers and the number of negative integers.",
        "difficulty": "easy",
        "order": 50,
        "chapter": "Prefix Sum & Two Pointers",
        "chapter_order": 7,
        "node_type": "boss",
        "starter_code_python": "class Solution:\n    def maximum_count(self, nums):\n        pass\n",
        "function_name": "maximum_count",
        "is_active": True,
        "tests": [
            test([[-2, -1, -1, 1, 2, 3]], 3, 1),
            test([[-3, -2, -1, 0, 0, 1, 2]], 3, 2),
            test([[0, 0, 0]], 0, 3, is_hidden=True),
        ],
    },
]


def normalize_expected_output(level_slug, expected_output):
    return expected_output


class Command(BaseCommand):
    help = "Seed LeetGame levels and test cases"

    def handle(self, *args, **options):
        total_levels = 0
        total_tests = 0

        for item in LEVELS_DATA:
            level_data = {k: v for k, v in item.items() if k != "tests"}
            tests = item["tests"]

            level, created = Level.objects.update_or_create(
                slug=level_data["slug"],
                defaults=level_data,
            )

            level.test_cases.all().delete()

            for case in tests:
                LevelTestCase.objects.create(
                    level=level,
                    input_data=case["input_data"],
                    expected_output=normalize_expected_output(level.slug, case["expected_output"]),
                    is_hidden=case["is_hidden"],
                    order=case["order"],
                )
                total_tests += 1

            total_levels += 1
            self.stdout.write(
                self.style.SUCCESS(
                    f"{'Created' if created else 'Updated'} level: {level.title}"
                )
            )

        self.stdout.write(
            self.style.SUCCESS(
                f"Finished seeding {total_levels} levels and {total_tests} test cases."
            )
        )
