from django.core.management.base import BaseCommand
from levels.models import Level, LevelTestCase


def visible(input_data, expected_output, order):
    return {
        "input_data": input_data,
        "expected_output": expected_output,
        "is_hidden": False,
        "order": order,
    }


def hidden(input_data, expected_output, order):
    return {
        "input_data": input_data,
        "expected_output": expected_output,
        "is_hidden": True,
        "order": order,
    }


LEVELS_DATA = [
    # ===========================
    # Chapter 1 — Arrays
    # ===========================
    {
        "title": "Two Sum",
        "slug": "two-sum",
        "description": "Return the indices of the two numbers such that they add up to target.",
        "difficulty": "easy",
        "order": 1,
        "chapter": "Arrays",
        "chapter_order": 1,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def two_sum(self, nums, target):\n        pass\n",
        "function_name": "two_sum",
        "is_active": True,
        "tests": [
            visible([[2, 7, 11, 15], 9], [0, 1], 1),
            visible([[3, 2, 4], 6], [1, 2], 2),
            hidden([[3, 3], 6], [0, 1], 3),
            hidden([[1, 5, 2, 7], 8], [0, 3], 4),
            hidden([[10, -2, 8, 4], 2], [1, 3], 5),
        ],
    },
    {
        "title": "Contains Duplicate",
        "slug": "contains-duplicate",
        "description": "Return true if any value appears at least twice in the array.",
        "difficulty": "easy",
        "order": 2,
        "chapter": "Arrays",
        "chapter_order": 1,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def contains_duplicate(self, nums):\n        pass\n",
        "function_name": "contains_duplicate",
        "is_active": True,
        "tests": [
            visible([[1, 2, 3, 1]], True, 1),
            visible([[1, 2, 3, 4]], False, 2),
            hidden([[1, 1, 1, 3, 3, 4, 3, 2, 4, 2]], True, 3),
            hidden([[]], False, 4),
            hidden([[5]], False, 5),
        ],
    },
    {
        "title": "Maximum Subarray",
        "slug": "maximum-subarray",
        "description": "Return the largest sum of any contiguous subarray.",
        "difficulty": "easy",
        "order": 3,
        "chapter": "Arrays",
        "chapter_order": 1,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def max_sub_array(self, nums):\n        pass\n",
        "function_name": "max_sub_array",
        "is_active": True,
        "tests": [
            visible([[-2,1,-3,4,-1,2,1,-5,4]], 6, 1),
            visible([[1]], 1, 2),
            hidden([[5,4,-1,7,8]], 23, 3),
            hidden([[-1,-2,-3,-4]], -1, 4),
            hidden([[0,0,0,0]], 0, 5),
        ],
    },
    {
        "title": "Product of Array Except Self",
        "slug": "product-of-array-except-self",
        "description": "Return an array where each element is the product of all other elements.",
        "difficulty": "medium",
        "order": 4,
        "chapter": "Arrays",
        "chapter_order": 1,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def product_except_self(self, nums):\n        pass\n",
        "function_name": "product_except_self",
        "is_active": True,
        "tests": [
            visible([[1,2,3,4]], [24,12,8,6], 1),
            visible([[-1,1,0,-3,3]], [0,0,9,0,0], 2),
            hidden([[2,3,4,5]], [60,40,30,24], 3),
            hidden([[0,0]], [0,0], 4),
            hidden([[5]], [1], 5),
        ],
    },
    {
        "title": "Best Time to Buy and Sell Stock",
        "slug": "best-time-to-buy-and-sell-stock",
        "description": "Return the maximum profit from one buy and one sell.",
        "difficulty": "easy",
        "order": 5,
        "chapter": "Arrays",
        "chapter_order": 1,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def max_profit(self, prices):\n        pass\n",
        "function_name": "max_profit",
        "is_active": True,
        "tests": [
            visible([[7,1,5,3,6,4]], 5, 1),
            visible([[7,6,4,3,1]], 0, 2),
            hidden([[2,4,1]], 2, 3),
            hidden([[1,2]], 1, 4),
            hidden([[2,1,2,1,0,1,2]], 2, 5),
        ],
    },
    {
        "title": "Find Pivot Index",
        "slug": "find-pivot-index",
        "description": "Return the pivot index where left sum equals right sum.",
        "difficulty": "easy",
        "order": 6,
        "chapter": "Arrays",
        "chapter_order": 1,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def pivot_index(self, nums):\n        pass\n",
        "function_name": "pivot_index",
        "is_active": True,
        "tests": [
            visible([[1,7,3,6,5,6]], 3, 1),
            visible([[1,2,3]], -1, 2),
            hidden([[2,1,-1]], 0, 3),
            hidden([[0,0,0,0]], 0, 4),
            hidden([[-1,-1,-1,0,1,1]], 0, 5),
        ],
    },
    {
        "title": "Majority Element",
        "slug": "majority-element",
        "description": "Return the majority element.",
        "difficulty": "easy",
        "order": 7,
        "chapter": "Arrays",
        "chapter_order": 1,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def majority_element(self, nums):\n        pass\n",
        "function_name": "majority_element",
        "is_active": True,
        "tests": [
            visible([[3,2,3]], 3, 1),
            visible([[2,2,1,1,1,2,2]], 2, 2),
            hidden([[1]], 1, 3),
            hidden([[6,5,5]], 5, 4),
            hidden([[9,9,9,1,2]], 9, 5),
        ],
    },
    {
        "title": "Missing Number",
        "slug": "missing-number",
        "description": "Return the missing number in the range [0, n].",
        "difficulty": "easy",
        "order": 8,
        "chapter": "Arrays",
        "chapter_order": 1,
        "node_type": "boss",
        "starter_code_python": "class Solution:\n    def missing_number(self, nums):\n        pass\n",
        "function_name": "missing_number",
        "is_active": True,
        "tests": [
            visible([[3,0,1]], 2, 1),
            visible([[0,1]], 2, 2),
            hidden([[9,6,4,2,3,5,7,0,1]], 8, 3),
            hidden([[1]], 0, 4),
            hidden([[0]], 1, 5),
        ],
    },

    # ===========================
    # Chapter 2 — Hashing
    # ===========================
    {
        "title": "Valid Anagram",
        "slug": "valid-anagram",
        "description": "Return true if t is an anagram of s.",
        "difficulty": "easy",
        "order": 9,
        "chapter": "Hashing",
        "chapter_order": 2,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def is_anagram(self, s, t):\n        pass\n",
        "function_name": "is_anagram",
        "is_active": True,
        "tests": [
            visible(["anagram", "nagaram"], True, 1),
            visible(["rat", "car"], False, 2),
            hidden(["aacc", "ccac"], False, 3),
            hidden(["", ""], True, 4),
            hidden(["listen", "silent"], True, 5),
        ],
    },
    {
        "title": "Ransom Note",
        "slug": "ransom-note",
        "description": "Return true if ransomNote can be constructed from magazine.",
        "difficulty": "easy",
        "order": 10,
        "chapter": "Hashing",
        "chapter_order": 2,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def can_construct(self, ransom_note, magazine):\n        pass\n",
        "function_name": "can_construct",
        "is_active": True,
        "tests": [
            visible(["a", "b"], False, 1),
            visible(["aa", "aab"], True, 2),
            hidden(["abc", "cbad"], True, 3),
            hidden(["hello", "helo"], False, 4),
            hidden(["", "anything"], True, 5),
        ],
    },
    {
        "title": "Isomorphic Strings",
        "slug": "isomorphic-strings",
        "description": "Return true if two strings are isomorphic.",
        "difficulty": "easy",
        "order": 11,
        "chapter": "Hashing",
        "chapter_order": 2,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def is_isomorphic(self, s, t):\n        pass\n",
        "function_name": "is_isomorphic",
        "is_active": True,
        "tests": [
            visible(["egg", "add"], True, 1),
            visible(["foo", "bar"], False, 2),
            hidden(["paper", "title"], True, 3),
            hidden(["badc", "baba"], False, 4),
            hidden(["13", "42"], True, 5),
        ],
    },
    {
        "title": "Word Pattern",
        "slug": "word-pattern",
        "description": "Return true if s follows the same pattern.",
        "difficulty": "easy",
        "order": 12,
        "chapter": "Hashing",
        "chapter_order": 2,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def word_pattern(self, pattern, s):\n        pass\n",
        "function_name": "word_pattern",
        "is_active": True,
        "tests": [
            visible(["abba", "dog cat cat dog"], True, 1),
            visible(["abba", "dog cat cat fish"], False, 2),
            hidden(["aaaa", "dog cat cat dog"], False, 3),
            hidden(["abba", "dog dog dog dog"], False, 4),
            hidden(["abc", "one two three"], True, 5),
        ],
    },
    {
        "title": "Happy Number",
        "slug": "happy-number",
        "description": "Return true if n is a happy number.",
        "difficulty": "easy",
        "order": 13,
        "chapter": "Hashing",
        "chapter_order": 2,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def is_happy(self, n):\n        pass\n",
        "function_name": "is_happy",
        "is_active": True,
        "tests": [
            visible([19], True, 1),
            visible([2], False, 2),
            hidden([1], True, 3),
            hidden([7], True, 4),
            hidden([20], False, 5),
        ],
    },
    {
        "title": "Longest Consecutive Sequence",
        "slug": "longest-consecutive-sequence",
        "description": "Return the length of the longest consecutive elements sequence.",
        "difficulty": "medium",
        "order": 14,
        "chapter": "Hashing",
        "chapter_order": 2,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def longest_consecutive(self, nums):\n        pass\n",
        "function_name": "longest_consecutive",
        "is_active": True,
        "tests": [
            visible([[100,4,200,1,3,2]], 4, 1),
            visible([[0,3,7,2,5,8,4,6,0,1]], 9, 2),
            hidden([[]], 0, 3),
            hidden([[1,2,0,1]], 3, 4),
            hidden([[9]], 1, 5),
        ],
    },
    {
        "title": "Find the Difference",
        "slug": "find-the-difference",
        "description": "Return the letter that was added to t.",
        "difficulty": "easy",
        "order": 15,
        "chapter": "Hashing",
        "chapter_order": 2,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def find_the_difference(self, s, t):\n        pass\n",
        "function_name": "find_the_difference",
        "is_active": True,
        "tests": [
            visible(["abcd", "abcde"], "e", 1),
            visible(["", "y"], "y", 2),
            hidden(["ae", "aea"], "a", 3),
            hidden(["hello", "ohllel"], "l", 4),
            hidden(["xyz", "xyzz"], "z", 5),
        ],
    },
    {
        "title": "First Unique Character in a String",
        "slug": "first-unique-character-in-a-string",
        "description": "Return the index of the first non-repeating character.",
        "difficulty": "easy",
        "order": 16,
        "chapter": "Hashing",
        "chapter_order": 2,
        "node_type": "boss",
        "starter_code_python": "class Solution:\n    def first_uniq_char(self, s):\n        pass\n",
        "function_name": "first_uniq_char",
        "is_active": True,
        "tests": [
            visible(["leetcode"], 0, 1),
            visible(["loveleetcode"], 2, 2),
            hidden(["aabb"], -1, 3),
            hidden(["z"], 0, 4),
            hidden(["swiss"], 1, 5),
        ],
    },

    # ===========================
    # Chapter 3 — Strings
    # ===========================
    {
        "title": "Valid Palindrome",
        "slug": "valid-palindrome",
        "description": "Return true if s is a palindrome after removing non-alphanumeric characters.",
        "difficulty": "easy",
        "order": 17,
        "chapter": "Strings",
        "chapter_order": 3,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def is_palindrome(self, s):\n        pass\n",
        "function_name": "is_palindrome",
        "is_active": True,
        "tests": [
            visible(["A man, a plan, a canal: Panama"], True, 1),
            visible(["race a car"], False, 2),
            hidden([" "], True, 3),
            hidden(["0P"], False, 4),
            hidden(["Madam"], True, 5),
        ],
    },
    {
        "title": "Longest Common Prefix",
        "slug": "longest-common-prefix",
        "description": "Return the longest common prefix string among an array of strings.",
        "difficulty": "easy",
        "order": 18,
        "chapter": "Strings",
        "chapter_order": 3,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def longest_common_prefix(self, strs):\n        pass\n",
        "function_name": "longest_common_prefix",
        "is_active": True,
        "tests": [
            visible([["flower", "flow", "flight"]], "fl", 1),
            visible([["dog", "racecar", "car"]], "", 2),
            hidden([["interspecies", "interstellar", "interstate"]], "inters", 3),
            hidden([["a"]], "a", 4),
            hidden([["ab", "a"]], "a", 5),
        ],
    },
    {
        "title": "Merge Strings Alternately",
        "slug": "merge-strings-alternately",
        "description": "Merge two strings by alternating letters.",
        "difficulty": "easy",
        "order": 19,
        "chapter": "Strings",
        "chapter_order": 3,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def merge_alternately(self, word1, word2):\n        pass\n",
        "function_name": "merge_alternately",
        "is_active": True,
        "tests": [
            visible(["abc", "pqr"], "apbqcr", 1),
            visible(["ab", "pqrs"], "apbqrs", 2),
            hidden(["abcd", "pq"], "apbqcd", 3),
            hidden(["", "xyz"], "xyz", 4),
            hidden(["m", "n"], "mn", 5),
        ],
    },
    {
        "title": "Reverse Words in a String III",
        "slug": "reverse-words-in-a-string-iii",
        "description": "Reverse the characters of each word in a sentence.",
        "difficulty": "easy",
        "order": 20,
        "chapter": "Strings",
        "chapter_order": 3,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def reverse_words(self, s):\n        pass\n",
        "function_name": "reverse_words",
        "is_active": True,
        "tests": [
            visible(["Let's take LeetCode contest"], "s'teL ekat edoCteeL tsetnoc", 1),
            visible(["God Ding"], "doG gniD", 2),
            hidden(["a b c"], "a b c", 3),
            hidden(["hello"], "olleh", 4),
            hidden(["ab cd"], "ba dc", 5),
        ],
    },
    {
        "title": "Length of Last Word",
        "slug": "length-of-last-word",
        "description": "Return the length of the last word in the string.",
        "difficulty": "easy",
        "order": 21,
        "chapter": "Strings",
        "chapter_order": 3,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def length_of_last_word(self, s):\n        pass\n",
        "function_name": "length_of_last_word",
        "is_active": True,
        "tests": [
            visible(["Hello World"], 5, 1),
            visible(["   fly me   to   the moon  "], 4, 2),
            hidden(["luffy is still joyboy"], 6, 3),
            hidden(["a"], 1, 4),
            hidden(["day"], 3, 5),
        ],
    },
    {
        "title": "Roman to Integer",
        "slug": "roman-to-integer",
        "description": "Convert a Roman numeral to an integer.",
        "difficulty": "easy",
        "order": 22,
        "chapter": "Strings",
        "chapter_order": 3,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def roman_to_int(self, s):\n        pass\n",
        "function_name": "roman_to_int",
        "is_active": True,
        "tests": [
            visible(["III"], 3, 1),
            visible(["LVIII"], 58, 2),
            hidden(["MCMXCIV"], 1994, 3),
            hidden(["IX"], 9, 4),
            hidden(["XL"], 40, 5),
        ],
    },
    {
        "title": "Valid Palindrome II",
        "slug": "valid-palindrome-ii",
        "description": "Return true if the string can be a palindrome after deleting at most one character.",
        "difficulty": "easy",
        "order": 23,
        "chapter": "Strings",
        "chapter_order": 3,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def valid_palindrome(self, s):\n        pass\n",
        "function_name": "valid_palindrome",
        "is_active": True,
        "tests": [
            visible(["aba"], True, 1),
            visible(["abca"], True, 2),
            hidden(["abc"], False, 3),
            hidden(["deeee"], True, 4),
            hidden(["cbbcc"], True, 5),
        ],
    },
    {
        "title": "Zigzag Conversion",
        "slug": "zigzag-conversion",
        "description": "Convert a string to zigzag form and read line by line.",
        "difficulty": "medium",
        "order": 24,
        "chapter": "Strings",
        "chapter_order": 3,
        "node_type": "boss",
        "starter_code_python": "class Solution:\n    def convert(self, s, num_rows):\n        pass\n",
        "function_name": "convert",
        "is_active": True,
        "tests": [
            visible(["PAYPALISHIRING", 3], "PAHNAPLSIIGYIR", 1),
            visible(["PAYPALISHIRING", 4], "PINALSIGYAHRPI", 2),
            hidden(["A", 1], "A", 3),
            hidden(["AB", 1], "AB", 4),
            hidden(["ABCDE", 2], "ACEBD", 5),
        ],
    },

    # ===========================
    # Chapter 4 — Stacks
    # ===========================
    {
        "title": "Valid Parentheses",
        "slug": "valid-parentheses",
        "description": "Return true if the brackets are valid.",
        "difficulty": "easy",
        "order": 25,
        "chapter": "Stacks",
        "chapter_order": 4,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def is_valid(self, s):\n        pass\n",
        "function_name": "is_valid",
        "is_active": True,
        "tests": [
            visible(["()"], True, 1),
            visible(["()[]{}"], True, 2),
            hidden(["(]"], False, 3),
            hidden(["([)]"], False, 4),
            hidden(["{[]}"], True, 5),
        ],
    },
    {
        "title": "Baseball Game",
        "slug": "baseball-game",
        "description": "Return the total score after applying the operations.",
        "difficulty": "easy",
        "order": 26,
        "chapter": "Stacks",
        "chapter_order": 4,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def cal_points(self, operations):\n        pass\n",
        "function_name": "cal_points",
        "is_active": True,
        "tests": [
            visible([["5", "2", "C", "D", "+"]], 30, 1),
            visible([["5", "-2", "4", "C", "D", "9", "+", "+"]], 27, 2),
            hidden([["1"]], 1, 3),
            hidden([["1", "C"]], 0, 4),
            hidden([["3", "D", "+"]], 15, 5),
        ],
    },
    {
        "title": "Remove All Adjacent Duplicates In String",
        "slug": "remove-all-adjacent-duplicates-in-string",
        "description": "Remove adjacent duplicate characters repeatedly.",
        "difficulty": "easy",
        "order": 27,
        "chapter": "Stacks",
        "chapter_order": 4,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def remove_duplicates(self, s):\n        pass\n",
        "function_name": "remove_duplicates",
        "is_active": True,
        "tests": [
            visible(["abbaca"], "ca", 1),
            visible(["azxxzy"], "ay", 2),
            hidden(["a"], "a", 3),
            hidden(["aaaaaaaa"], "", 4),
            hidden(["abba"], "", 5),
        ],
    },
    {
        "title": "Make The String Great",
        "slug": "make-the-string-great",
        "description": "Remove adjacent same letters with opposite cases until the string is good.",
        "difficulty": "easy",
        "order": 28,
        "chapter": "Stacks",
        "chapter_order": 4,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def make_good(self, s):\n        pass\n",
        "function_name": "make_good",
        "is_active": True,
        "tests": [
            visible(["leEeetcode"], "leetcode", 1),
            visible(["abBAcC"], "", 2),
            hidden(["s"], "s", 3),
            hidden(["Pp"], "", 4),
            hidden(["mCcaA"], "m", 5),
        ],
    },
    {
        "title": "Backspace String Compare",
        "slug": "backspace-string-compare",
        "description": "Return true if two strings are equal after processing backspaces.",
        "difficulty": "easy",
        "order": 29,
        "chapter": "Stacks",
        "chapter_order": 4,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def backspace_compare(self, s, t):\n        pass\n",
        "function_name": "backspace_compare",
        "is_active": True,
        "tests": [
            visible(["ab#c", "ad#c"], True, 1),
            visible(["ab##", "c#d#"], True, 2),
            hidden(["a#c", "b"], False, 3),
            hidden(["xywrrmp", "xywrrmu#p"], True, 4),
            hidden(["nzp#o#g", "b#nzp#o#g"], True, 5),
        ],
    },
    {
        "title": "Min Add to Make Parentheses Valid",
        "slug": "min-add-to-make-parentheses-valid",
        "description": "Return the minimum number of parentheses needed to make the string valid.",
        "difficulty": "medium",
        "order": 30,
        "chapter": "Stacks",
        "chapter_order": 4,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def min_add_to_make_valid(self, s):\n        pass\n",
        "function_name": "min_add_to_make_valid",
        "is_active": True,
        "tests": [
            visible(["())"], 1, 1),
            visible(["((("], 3, 2),
            hidden(["()"], 0, 3),
            hidden(["()))(("], 4, 4),
            hidden(["()))"], 1, 5),
        ],
    },
    {
        "title": "Evaluate Reverse Polish Notation",
        "slug": "evaluate-reverse-polish-notation",
        "description": "Evaluate the value of an arithmetic expression in Reverse Polish Notation.",
        "difficulty": "medium",
        "order": 31,
        "chapter": "Stacks",
        "chapter_order": 4,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def eval_rpn(self, tokens):\n        pass\n",
        "function_name": "eval_rpn",
        "is_active": True,
        "tests": [
            visible([["2", "1", "+", "3", "*"]], 9, 1),
            visible([["4", "13", "5", "/", "+"]], 6, 2),
            hidden([["10", "6", "9", "3", "+", "-11", "*", "/", "*", "17", "+", "5", "+"]], 22, 3),
            hidden([["3", "4", "+"]], 7, 4),
            hidden([["5"]], 5, 5),
        ],
    },
    {
        "title": "Decode String",
        "slug": "decode-string",
        "description": "Decode an encoded string like 3[a2[c]].",
        "difficulty": "medium",
        "order": 32,
        "chapter": "Stacks",
        "chapter_order": 4,
        "node_type": "boss",
        "starter_code_python": "class Solution:\n    def decode_string(self, s):\n        pass\n",
        "function_name": "decode_string",
        "is_active": True,
        "tests": [
            visible(["3[a]2[bc]"], "aaabcbc", 1),
            visible(["3[a2[c]]"], "accaccacc", 2),
            hidden(["2[abc]3[cd]ef"], "abcabccdcdcdef", 3),
            hidden(["abc3[cd]xyz"], "abccdcdcdxyz", 4),
            hidden(["10[a]"], "aaaaaaaaaa", 5),
        ],
    },

    # ===========================
    # Chapter 5 — Binary Search
    # ===========================
    {
        "title": "Binary Search",
        "slug": "binary-search",
        "description": "Return the index of target in a sorted array, or -1 if not found.",
        "difficulty": "easy",
        "order": 33,
        "chapter": "Binary Search",
        "chapter_order": 5,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def search(self, nums, target):\n        pass\n",
        "function_name": "search",
        "is_active": True,
        "tests": [
            visible([[-1,0,3,5,9,12], 9], 4, 1),
            visible([[-1,0,3,5,9,12], 2], -1, 2),
            hidden([[5], 5], 0, 3),
            hidden([[1,2,3,4,5], 1], 0, 4),
            hidden([[1,2,3,4,5], 5], 4, 5),
        ],
    },
    {
        "title": "Search Insert Position",
        "slug": "search-insert-position",
        "description": "Return the index if found, or the position where target should be inserted.",
        "difficulty": "easy",
        "order": 34,
        "chapter": "Binary Search",
        "chapter_order": 5,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def search_insert(self, nums, target):\n        pass\n",
        "function_name": "search_insert",
        "is_active": True,
        "tests": [
            visible([[1,3,5,6], 5], 2, 1),
            visible([[1,3,5,6], 2], 1, 2),
            hidden([[1,3,5,6], 7], 4, 3),
            hidden([[1,3,5,6], 0], 0, 4),
            hidden([[1], 0], 0, 5),
        ],
    },
    {
        "title": "Sqrt(x)",
        "slug": "sqrtx",
        "description": "Return the integer square root of x.",
        "difficulty": "easy",
        "order": 35,
        "chapter": "Binary Search",
        "chapter_order": 5,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def my_sqrt(self, x):\n        pass\n",
        "function_name": "my_sqrt",
        "is_active": True,
        "tests": [
            visible([4], 2, 1),
            visible([8], 2, 2),
            hidden([0], 0, 3),
            hidden([1], 1, 4),
            hidden([15], 3, 5),
        ],
    },
    {
        "title": "Arrange Coins",
        "slug": "arrange-coins",
        "description": "Return the number of complete staircase rows that can be formed.",
        "difficulty": "easy",
        "order": 36,
        "chapter": "Binary Search",
        "chapter_order": 5,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def arrange_coins(self, n):\n        pass\n",
        "function_name": "arrange_coins",
        "is_active": True,
        "tests": [
            visible([5], 2, 1),
            visible([8], 3, 2),
            hidden([1], 1, 3),
            hidden([3], 2, 4),
            hidden([10], 4, 5),
        ],
    },
    {
        "title": "Find Smallest Letter Greater Than Target",
        "slug": "find-smallest-letter-greater-than-target",
        "description": "Return the smallest character that is lexicographically greater than target.",
        "difficulty": "easy",
        "order": 37,
        "chapter": "Binary Search",
        "chapter_order": 5,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def next_greatest_letter(self, letters, target):\n        pass\n",
        "function_name": "next_greatest_letter",
        "is_active": True,
        "tests": [
            visible([["c","f","j"], "a"], "c", 1),
            visible([["c","f","j"], "c"], "f", 2),
            hidden([["c","f","j"], "d"], "f", 3),
            hidden([["c","f","j"], "g"], "j", 4),
            hidden([["c","f","j"], "j"], "c", 5),
        ],
    },
    {
        "title": "Peak Index in Mountain Array",
        "slug": "peak-index-in-mountain-array",
        "description": "Return the index of the peak element in a mountain array.",
        "difficulty": "easy",
        "order": 38,
        "chapter": "Binary Search",
        "chapter_order": 5,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def peak_index_in_mountain_array(self, arr):\n        pass\n",
        "function_name": "peak_index_in_mountain_array",
        "is_active": True,
        "tests": [
            visible([[0,1,0]], 1, 1),
            visible([[0,2,1,0]], 1, 2),
            hidden([[0,10,5,2]], 1, 3),
            hidden([[3,4,5,1]], 2, 4),
            hidden([[24,69,100,99,79,78,67,36,26,19]], 2, 5),
        ],
    },
    {
        "title": "Search in Rotated Sorted Array",
        "slug": "search-in-rotated-sorted-array",
        "description": "Return the index of target in a rotated sorted array, or -1 if not found.",
        "difficulty": "medium",
        "order": 39,
        "chapter": "Binary Search",
        "chapter_order": 5,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def search(self, nums, target):\n        pass\n",
        "function_name": "search",
        "is_active": True,
        "tests": [
            visible([[4,5,6,7,0,1,2], 0], 4, 1),
            visible([[4,5,6,7,0,1,2], 3], -1, 2),
            hidden([[1], 0], -1, 3),
            hidden([[1], 1], 0, 4),
            hidden([[5,1,3], 5], 0, 5),
        ],
    },
    {
        "title": "Koko Eating Bananas",
        "slug": "koko-eating-bananas",
        "description": "Return the minimum eating speed to finish all bananas within h hours.",
        "difficulty": "medium",
        "order": 40,
        "chapter": "Binary Search",
        "chapter_order": 5,
        "node_type": "boss",
        "starter_code_python": "class Solution:\n    def min_eating_speed(self, piles, h):\n        pass\n",
        "function_name": "min_eating_speed",
        "is_active": True,
        "tests": [
            visible([[3,6,7,11], 8], 4, 1),
            visible([[30,11,23,4,20], 5], 30, 2),
            hidden([[30,11,23,4,20], 6], 23, 3),
            hidden([[312884470], 312884469], 2, 4),
            hidden([[1,1,1,1], 4], 1, 5),
        ],
    },

    # ===========================
    # Chapter 6 — Sliding Window
    # ===========================
    {
        "title": "Maximum Average Subarray I",
        "slug": "maximum-average-subarray-i",
        "description": "Return the maximum average value of any contiguous subarray of length k.",
        "difficulty": "easy",
        "order": 41,
        "chapter": "Sliding Window",
        "chapter_order": 6,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def find_max_average(self, nums, k):\n        pass\n",
        "function_name": "find_max_average",
        "is_active": True,
        "tests": [
            visible([[1,12,-5,-6,50,3], 4], 12.75, 1),
            visible([[5], 1], 5.0, 2),
            hidden([[0,4,0,3,2], 1], 4.0, 3),
            hidden([[1,1,1,1], 2], 1.0, 4),
            hidden([[-1,-12,-5,-6,-50,-3], 2], -5.5, 5),
        ],
    },
    {
        "title": "Longest Substring Without Repeating Characters",
        "slug": "longest-substring-without-repeating-characters",
        "description": "Return the length of the longest substring without repeating characters.",
        "difficulty": "medium",
        "order": 42,
        "chapter": "Sliding Window",
        "chapter_order": 6,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def length_of_longest_substring(self, s):\n        pass\n",
        "function_name": "length_of_longest_substring",
        "is_active": True,
        "tests": [
            visible(["abcabcbb"], 3, 1),
            visible(["bbbbb"], 1, 2),
            hidden(["pwwkew"], 3, 3),
            hidden([""], 0, 4),
            hidden(["dvdf"], 3, 5),
        ],
    },
    {
        "title": "Permutation in String",
        "slug": "permutation-in-string",
        "description": "Return true if s2 contains a permutation of s1.",
        "difficulty": "medium",
        "order": 43,
        "chapter": "Sliding Window",
        "chapter_order": 6,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def check_inclusion(self, s1, s2):\n        pass\n",
        "function_name": "check_inclusion",
        "is_active": True,
        "tests": [
            visible(["ab", "eidbaooo"], True, 1),
            visible(["ab", "eidboaoo"], False, 2),
            hidden(["adc", "dcda"], True, 3),
            hidden(["hello", "ooolleoooleh"], False, 4),
            hidden(["xyz", "afdgzyxksldfm"], True, 5),
        ],
    },
    {
        "title": "Minimum Size Subarray Sum",
        "slug": "minimum-size-subarray-sum",
        "description": "Return the minimal length of a subarray with sum at least target.",
        "difficulty": "medium",
        "order": 44,
        "chapter": "Sliding Window",
        "chapter_order": 6,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def min_sub_array_len(self, target, nums):\n        pass\n",
        "function_name": "min_sub_array_len",
        "is_active": True,
        "tests": [
            visible([7, [2,3,1,2,4,3]], 2, 1),
            visible([4, [1,4,4]], 1, 2),
            hidden([11, [1,1,1,1,1,1,1,1]], 0, 3),
            hidden([15, [1,2,3,4,5]], 5, 4),
            hidden([6, [10,2,3]], 1, 5),
        ],
    },
    {
        "title": "Longest Repeating Character Replacement",
        "slug": "longest-repeating-character-replacement",
        "description": "Return the length of the longest substring obtainable after at most k replacements.",
        "difficulty": "medium",
        "order": 45,
        "chapter": "Sliding Window",
        "chapter_order": 6,
        "node_type": "boss",
        "starter_code_python": "class Solution:\n    def character_replacement(self, s, k):\n        pass\n",
        "function_name": "character_replacement",
        "is_active": True,
        "tests": [
            visible(["ABAB", 2], 4, 1),
            visible(["AABABBA", 1], 4, 2),
            hidden(["AAAA", 2], 4, 3),
            hidden(["ABCDE", 1], 2, 4),
            hidden(["BAAAB", 2], 5, 5),
        ],
    },

    # ===========================
    # Chapter 7 — Prefix Sum & Two Pointers
    # ===========================
    {
        "title": "Squares of a Sorted Array",
        "slug": "squares-of-a-sorted-array",
        "description": "Return the squares of each number sorted in non-decreasing order.",
        "difficulty": "easy",
        "order": 46,
        "chapter": "Prefix Sum & Two Pointers",
        "chapter_order": 7,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def sorted_squares(self, nums):\n        pass\n",
        "function_name": "sorted_squares",
        "is_active": True,
        "tests": [
            visible([[-4,-1,0,3,10]], [0,1,9,16,100], 1),
            visible([[-7,-3,2,3,11]], [4,9,9,49,121], 2),
            hidden([[0]], [0], 3),
            hidden([[-2,-1]], [1,4], 4),
            hidden([[1,2,3]], [1,4,9], 5),
        ],
    },
    {
        "title": "Running Sum of 1d Array",
        "slug": "running-sum-of-1d-array",
        "description": "Return the running sum of the array.",
        "difficulty": "easy",
        "order": 47,
        "chapter": "Prefix Sum & Two Pointers",
        "chapter_order": 7,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def running_sum(self, nums):\n        pass\n",
        "function_name": "running_sum",
        "is_active": True,
        "tests": [
            visible([[1,2,3,4]], [1,3,6,10], 1),
            visible([[1,1,1,1,1]], [1,2,3,4,5], 2),
            hidden([[3,1,2,10,1]], [3,4,6,16,17], 3),
            hidden([[]], [], 4),
            hidden([[5]], [5], 5),
        ],
    },
    {
        "title": "Find Middle Index in Array",
        "slug": "find-middle-index-in-array",
        "description": "Return the leftmost index where left sum equals right sum.",
        "difficulty": "easy",
        "order": 48,
        "chapter": "Prefix Sum & Two Pointers",
        "chapter_order": 7,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def find_middle_index(self, nums):\n        pass\n",
        "function_name": "find_middle_index",
        "is_active": True,
        "tests": [
            visible([[2,3,-1,8,4]], 3, 1),
            visible([[1,-1,4]], 2, 2),
            hidden([[2,5]], -1, 3),
            hidden([[1,1,1,1,1]], 2, 4),
            hidden([[0,0,0]], 0, 5),
        ],
    },
    {
        "title": "Subarray Sum Equals K",
        "slug": "subarray-sum-equals-k",
        "description": "Return the number of continuous subarrays whose sum equals k.",
        "difficulty": "medium",
        "order": 49,
        "chapter": "Prefix Sum & Two Pointers",
        "chapter_order": 7,
        "node_type": "normal",
        "starter_code_python": "class Solution:\n    def subarray_sum(self, nums, k):\n        pass\n",
        "function_name": "subarray_sum",
        "is_active": True,
        "tests": [
            visible([[1,1,1], 2], 2, 1),
            visible([[1,2,3], 3], 2, 2),
            hidden([[1,-1,0], 0], 3, 3),
            hidden([[3,4,7,2,-3,1,4,2], 7], 4, 4),
            hidden([[0,0,0], 0], 6, 5),
        ],
    },
    {
        "title": "Maximum Count of Positive Integer and Negative Integer",
        "slug": "maximum-count-of-positive-integer-and-negative-integer",
        "description": "Return the maximum of the count of positive integers and the count of negative integers.",
        "difficulty": "easy",
        "order": 50,
        "chapter": "Prefix Sum & Two Pointers",
        "chapter_order": 7,
        "node_type": "boss",
        "starter_code_python": "class Solution:\n    def maximum_count(self, nums):\n        pass\n",
        "function_name": "maximum_count",
        "is_active": True,
        "tests": [
            visible([[-2,-1,-1,1,2,3]], 3, 1),
            visible([[-3,-2,-1,0,0,1,2]], 3, 2),
            hidden([[5,20,66,1314]], 4, 3),
            hidden([[-5,-4,-3,-2,-1]], 5, 4),
            hidden([[0,0,0]], 0, 5),
        ],
    },
]


def normalize_expected_output(level_slug, expected_output):
    return expected_output


class Command(BaseCommand):
    help = "Seed 50 LeetGame levels and test cases"

    def handle(self, *args, **options):
        for item in LEVELS_DATA:
            tests = item.pop("tests", [])

            level, created = Level.objects.update_or_create(
                slug=item["slug"],
                defaults=item,
            )

            level.test_cases.all().delete()

            for test in tests:
                LevelTestCase.objects.create(
                    level=level,
                    input_data=test["input_data"],
                    expected_output=normalize_expected_output(level.slug, test["expected_output"]),
                    is_hidden=test["is_hidden"],
                    order=test["order"],
                )

            self.stdout.write(
                self.style.SUCCESS(
                    f"{'Created' if created else 'Updated'} level: {level.title}"
                )
            )

        self.stdout.write(self.style.SUCCESS("Finished seeding 50 levels and 250 test cases."))